<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'Mắt Biếc',
                'author_id' => 1,
                'category_id' => 3,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXOT4u65NshwoXWcVmOgmAijFVC7Uzbhgqmw&s',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 1990,
                'quantity' => 30,
                'available' => 30,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cho Tôi Xin Một Vé Đi Tuổi Thơ',
                'author_id' => 1,
                'category_id' => 3,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhVDxXtSTn1LifWeaK-NIszH9imr4FgmlNbA&s',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 2007,
                'quantity' => 25,
                'available' => 25,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cô Gái Đến Từ Hôm Qua',
                'author_id' => 1,
                'category_id' => 3,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf5pyipN2M1ziZ_s9aj_SO9Vr_EvNCoWi1HQ&s',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 1989,
                'quantity' => 20,
                'available' => 20,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chí Phèo',
                'author_id' => 2,
                'category_id' => 2,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThoihr05OKMM0Oy8QMiZLcq1XQF8CRDM87_A&s',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1941,
                'quantity' => 15,
                'available' => 15,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lão Hạc',
                'author_id' => 2,
                'category_id' => 2,
                'image' => 'https://isach.info/images/story/cover/lao_hac__nam_cao.jpg',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1943,
                'quantity' => 15,
                'available' => 15,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dế Mèn Phiêu Lưu Ký',
                'author_id' => 3,
                'category_id' => 3,
                'image' => 'https://isach.info/images/story/cover/de_men_phieu_luu_ky_ban_du__to_hoai.jpg',
                'publisher' => 'NXB Kim Đồng',
                'publication_year' => 1941,
                'quantity' => 40,
                'available' => 40,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Số Đỏ',
                'author_id' => 4,
                'category_id' => 1,
                'image' => 'https://isach.info/images/story/cover/de_men_phieu_luu_ky_ban_du__to_hoai.jpg',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1936,
                'quantity' => 18,
                'available' => 18,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Giông Tố',
                'author_id' => 4,
                'category_id' => 1,
                'image' => 'https://cdn1.fahasa.com/media/catalog/product/i/m/image_238410.jpg',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1936,
                'quantity' => 12,
                'available' => 12,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Thơ Thơ',
                'author_id' => 5,
                'category_id' => 4,
                'image' => 'https://www.thivien.net/attachment/0hbug-JMiRlGJApHaCX9fA.1707738268.webp',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1938,
                'quantity' => 10,
                'available' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nhật Ký Trong Tù',
                'author_id' => 6,
                'category_id' => 4,
                'image' => 'https://file3.qdnd.vn/data/images/0/2023/05/12/hoanghoang/a.jpg',
                'publisher' => 'NXB Chính Trị',
                'publication_year' => 1942,
                'quantity' => 22,
                'available' => 22,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Truyện Kiều',
                'author_id' => 7,
                'category_id' => 1,
                'image' => 'https://www.nxbtre.com.vn/Images/Book/NXBTreStoryFull_03462015_104616.jpg',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1820,
                'quantity' => 35,
                'available' => 35,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hà Nội Băm Sáu Phố Phường',
                'author_id' => 8,
                'category_id' => 5,
                'image' => 'https://cdn1.fahasa.com/media/catalog/product/8/9/8935236429818.jpg',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 1994,
                'quantity' => 8,
                'available' => 8,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hai Đứa Trẻ',
                'author_id' => 8,
                'category_id' => 2,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy1GoPrSwncFl4D_MAB2m6au3OLBN9Sx9nlw&s',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1941,
                'quantity' => 14,
                'available' => 14,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tướng Về Hưu',
                'author_id' => 9,
                'category_id' => 1,
                'image' => 'https://files01.duytan.edu.vn/svruploads/xhnv-duytan/upload/images/base64-1620366425904177205357.png',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 1987,
                'quantity' => 9,
                'available' => 9,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Không Có Vua',
                'author_id' => 9,
                'category_id' => 2,
                'image' => 'https://product.hstatic.net/200000979221/product/khong-co-vua_0824bf9cdeb6442992d6113643847f84_master.png',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 1988,
                'quantity' => 7,
                'available' => 7,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nỗi Buồn Chiến Tranh',
                'author_id' => 10,
                'category_id' => 1,
                'image' => 'https://www.nxbtre.com.vn/Images/Book/nxbtre_full_10152022_031532.jpg',
                'publisher' => 'NXB Trẻ',
                'publication_year' => 1990,
                'quantity' => 16,
                'available' => 16,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bến Không Chồng',
                'author_id' => 9,
                'category_id' => 1,
                'image' => 'https://www.nxbtre.com.vn/Images/Book/nxbtre_full_15592025_105952.jpg',
                'publisher' => 'NXB Phụ Nữ',
                'publication_year' => 1991,
                'quantity' => 11,
                'available' => 11,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Đất Rừng Phương Nam',
                'author_id' => 3,
                'category_id' => 3,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrY4GF58p7Cvjqcl2UhvL4MW6NPXPf94kTWQ&s',
                'publisher' => 'NXB Kim Đồng',
                'publication_year' => 1957,
                'quantity' => 13,
                'available' => 13,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vang Bóng Một Thời',
                'author_id' => 8,
                'category_id' => 2,
                'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNK4PiJxAnIACu6nzCWYHFEWT5X5TLN2FR_A&s',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1940,
                'quantity' => 6,
                'available' => 6,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vợ Nhặt',
                'author_id' => 2,
                'category_id' => 2,
                'image' => 'https://isach.info/images/story/cover/vo_nhat__kim_lan.jpg',
                'publisher' => 'NXB Văn Học',
                'publication_year' => 1962,
                'quantity' => 10,
                'available' => 10,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('books')->insert($books);
    }
}
